export const BREEDS_FETCHED = 'BREEDS_FETCHED';
export const DOGS_BY_BREEDS_FETCHED = 'DOGS_BY_BREEDS_FETCHED';
export const RANDOM_DOG_FETCHED = 'RANDOM_DOG_FETCHED';

export const BREEDS_SET = 'BREEDS_SET';
export const DOGS_SET = 'DOGS_SET';
export const SELECTED_DOG_SET = 'SELECTED_DOG_SET';

export const ERROR_SET = 'ERROR_SET';
export const LOADING_SET = 'LOADING_SET';
